const house = [
  {
    id: 1,
    title: 'Ayat Condominium',
    price: '60,000',
    location: 'Ayat, Addis Ababa',
    bedNo: 3,
    bathNo: 3,
    phone: '0978986512',
    area: 150,
    floor: 2,
    agentPhone: '0987654321',
    images: [
      require('../assets/house1.jpg'),
      require('../assets/heroImg.jpg'),
      require('../assets/house3.jpg'),
      require('../assets/house4.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 2,
    title: 'Lebu Condominium',
    price: '10,000',
    location: 'Lebu, Addis Ababa',
    bedNo: 2,
    bathNo: 2,
    phone: '0978986512',
    agentPhone: '0912345678',
    floor: 1,
    area: 90,
    images: [
      require('../assets/heroImg.jpg'),
      require('../assets/house1.jpg'),
      require('../assets/heroImg.jpg'),
      require('../assets/heroImg2.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 3,
    title: 'Jemo Condominium',
    price: '10,000',
    location: 'Jemo 2, Addis Ababa',
    bedNo: 3,
    phone: '0978986512',
    floor: 4,
    bathNo: 3,
    agentPhone: '0987654321',
    area: 200,
    images: [
      require('../assets/house4.jpg'),
      require('../assets/house2.jpg'),
      require('../assets/heroImg.jpg'),
      require('../assets/house1.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 4,
    title: 'Ledeta Condominium',
    price: '10,000',
    location: 'Ledeta, Addis Ababa',
    bedNo: 1,
    phone: '0978986512',
    agentPhone: '0912345678',
    floor: 5,
    bathNo: 1,
    area: 200,
    images: [
      require('../assets/house3.jpg'),
      require('../assets/heroImg2.jpg'),
      require('../assets/house4.jpg'),
      require('../assets/house2.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 5,
    title: 'Koye Feche Condominium',
    price: '10,000',
    location: 'Koye Feche, Addis Ababa',
    bedNo: 2,
    phone: '0978986512',
    agentPhone: '0987654321',
    floor: 1,
    bathNo: 2,
    area: 200,
    images: [
      require('../assets/house2.jpg'),
      require('../assets/house3.jpg'),
      require('../assets/heroImg.jpg'),
      require('../assets/house4.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 6,
    title: 'Jemo Condominium',
    price: '10,000',
    location: 'Jemo 3, Addis Ababa',
    bedNo: 3,
    phone: '0978986512',
    floor: 1,
    agentPhone: '0912345678',
    bathNo: 3,
    area: 200,
    images: [
      require('../assets/house3.jpg'),
      require('../assets/heroImg2.jpg'),
      require('../assets/house4.jpg'),
      require('../assets/house2.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 7,
    title: 'Apartment',
    price: '100,000',
    location: 'Sarbet, Addis Ababa',
    bedNo: 3,
    phone: '0978986512',
    agentPhone: '0987654321',
    bathNo: 3,
    floor: 3,
    area: 200,
    images: [
      require('../assets/house4.jpg'),
      require('../assets/heroImg2.jpg'),
      require('../assets/heroImg.jpg'),
      require('../assets/house3.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 8,
    title: 'Villa',
    price: '50,000',
    location: 'Mekanisa, Addis Ababa',
    bedNo: 5,
    phone: '0978986512',
    agentPhone: '0987654321',
    floor: 1,
    bathNo: 5,
    area: 200,
    images: [
      require('../assets/house2.jpg'),
      require('../assets/heroImg2.jpg'),
      require('../assets/heroImg.jpg'),
      require('../assets/house3.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 9,
    title: 'Condominium',
    price: '20,000',
    location: 'Jemo, Addis Ababa',
    bedNo: 3,
    phone: '0978986512',
    agentPhone: '0912345678',
    floor: 2,
    bathNo: 3,
    area: 250,
    images: [
      require('../assets/heroImg.jpg'),
      require('../assets/house4.jpg'),
      require('../assets/heroImg.jpg'),
      require('../assets/house2.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
  {
    id: 10,
    title: 'Apartment',
    price: '40,000',
    location: '6 kilo, Addis Ababa',
    bedNo: 2,
    phone: '0978986512',
    agentPhone: '0987654321',
    floor: 2,
    bathNo: 2,
    area: 230,
    images: [
      require('../assets/house3.jpg'),
      require('../assets/heroImg2.jpg'),
      require('../assets/heroImg.jpg'),
      require('../assets/house4.jpg'),
    ],
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ducimus suscipit fugiat illum repellat repudiandae dignissimos aliquid ad numquam praesentium ut.',
  },
];

export default house;
